server:
  port: 9002 #服务端口
spring:
  datasource:
    url: jdbc:mysql://cdb-jpqc2xft.gz.tencentcdb.com:10045/stock?&useSSL=false&characterEncoding=utf8
    username: ly
    password: ly123456


#mybatis:
#  mapper-locations: classpath*:com/tianhao/springcloudpayment/mapping/*
mybatis-plus:
  mapper-locations: classpath*:com/example/position/mapping/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


logging:
  level:
    com.example.position.dao : debug